using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ConduitNet.SourceGenerator
{
    [Generator]
    public class ConduitSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is SyntaxReceiver receiver))
                return;

            var classMap = receiver.TargetMethods
                .GroupBy(m => m.ContainingType, SymbolEqualityComparer.Default);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine("using ConduitNet;");
            sb.AppendLine();
            sb.AppendLine("namespace ConduitNet.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class ConduitGeneratedRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        {");

            foreach (var group in classMap)
            {
                var classSymbol = (INamedTypeSymbol)group.Key;
                if (classSymbol == null) continue;

                string className = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sb.AppendLine($"            ConduitNet.ConduitRegistry.GeneratedBinders[typeof({className})] = (component) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                var target = ({className})component;");

                foreach (var method in group)
                {
                    string methodName = method.Name;
                    
                    // Parse RequireRole
                    string senderRole = "ConduitNet.Role.Any";
                    string receiverRole = "ConduitNet.Role.Any";

                    var roleAttr = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "RequireRoleAttribute" || a.AttributeClass?.Name == "RequireRole");
                    if (roleAttr != null)
                    {
                        if (roleAttr.ConstructorArguments.Length > 0)
                            senderRole = "ConduitNet.Role." + roleAttr.ConstructorArguments[0].Value;
                        if (roleAttr.ConstructorArguments.Length > 1)
                            receiverRole = "ConduitNet.Role." + roleAttr.ConstructorArguments[1].Value;
                        
                        foreach(var named in roleAttr.NamedArguments) {
                            if (named.Key == "sender") senderRole = "ConduitNet.Role." + named.Value.Value;
                            if (named.Key == "receiver") receiverRole = "ConduitNet.Role." + named.Value.Value;
                        }
                    }

                    var bytesAttr = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "BytesHandlerAttribute" || a.AttributeClass?.Name == "BytesHandler");
                    var signalAttr = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "SignalHandlerAttribute" || a.AttributeClass?.Name == "SignalHandler");
                    var packetAttr = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "PacketHandlerAttribute" || a.AttributeClass?.Name == "PacketHandler");

                    sb.AppendLine("                {");
                    sb.AppendLine($"                    var method = typeof({className}).GetMethod(\"{methodName}\", BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance);");

                    if (bytesAttr != null)
                    {
                        sb.AppendLine($"                    var handler = (ConduitNet.BytesHandler)Delegate.CreateDelegate(typeof(ConduitNet.BytesHandler), target, method);");
                        sb.AppendLine($"                    target.InternalBindGeneratedBytesHandler(handler, {senderRole}, {receiverRole});");
                    }
                    else if (signalAttr != null && signalAttr.ConstructorArguments.Length > 0)
                    {
                        string signalName = signalAttr.ConstructorArguments[0].Value.ToString();
                        sb.AppendLine($"                    var handler = (ConduitNet.SignalHandler)Delegate.CreateDelegate(typeof(ConduitNet.SignalHandler), target, method);");
                        sb.AppendLine($"                    target.InternalBindGeneratedSignalHandler(\"{signalName}\", handler, {senderRole}, {receiverRole});");
                    }
                    else if (packetAttr != null)
                    {
                        // Get packet type from parameter
                        var param = method.Parameters.FirstOrDefault();
                        if (param != null && param.Type is INamedTypeSymbol namedParam && namedParam.IsGenericType)
                        {
                            var packetTypeArg = namedParam.TypeArguments.FirstOrDefault();
                            if (packetTypeArg != null)
                            {
                                string packetType = packetTypeArg.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                                sb.AppendLine($"                    var handler = (ConduitNet.PacketHandler<{packetType}>)Delegate.CreateDelegate(typeof(ConduitNet.PacketHandler<{packetType}>), target, method);");
                                sb.AppendLine($"                    target.InternalBindGeneratedPacketHandler<{packetType}>(handler, {senderRole}, {receiverRole});");
                            }
                        }
                    }
                    sb.AppendLine("                }");
                }
                sb.AppendLine("            };");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("ConduitGeneratedRegistry.g.cs", sb.ToString());
        }

        class SyntaxReceiver : ISyntaxContextReceiver
        {
            public List<IMethodSymbol> TargetMethods { get; } = new List<IMethodSymbol>();

            public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
            {
                if (context.Node is MethodDeclarationSyntax methodDecl && methodDecl.AttributeLists.Count > 0)
                {
                    var symbol = context.SemanticModel.GetDeclaredSymbol(methodDecl) as IMethodSymbol;
                    if (symbol == null) return;

                    bool hasTargetAttribute = symbol.GetAttributes().Any(ad => 
                        ad.AttributeClass != null && (
                        ad.AttributeClass.Name == "BytesHandlerAttribute" || 
                        ad.AttributeClass.Name == "SignalHandlerAttribute" || 
                        ad.AttributeClass.Name == "PacketHandlerAttribute"));

                    if (hasTargetAttribute)
                    {
                        TargetMethods.Add(symbol);
                    }
                }
            }
        }
    }
}
